/* ─────────────────────────────────────────────────────────────
   Code generator — produces a complete design system package
   compatible with quickly-react.
   ───────────────────────────────────────────────────────────── */

const FONT_NATIVE_NAMES = {
  'Inter':             { regular: 'Inter-Regular',       medium: 'Inter-Medium',       semiBold: 'Inter-SemiBold',       bold: 'Inter-Bold'       },
  'Poppins':           { regular: 'Poppins-Regular',     medium: 'Poppins-Medium',     semiBold: 'Poppins-SemiBold',     bold: 'Poppins-Bold'     },
  'DM Sans':           { regular: 'DMSans-Regular',      medium: 'DMSans-Medium',      semiBold: 'DMSans-SemiBold',      bold: 'DMSans-Bold'      },
  'Nunito':            { regular: 'Nunito-Regular',      medium: 'Nunito-Medium',      semiBold: 'Nunito-SemiBold',      bold: 'Nunito-Bold'      },
  'Outfit':            { regular: 'Outfit-Regular',      medium: 'Outfit-Medium',      semiBold: 'Outfit-SemiBold',      bold: 'Outfit-Bold'      },
  'Plus Jakarta Sans': { regular: 'PlusJakartaSans-Regular', medium: 'PlusJakartaSans-Medium', semiBold: 'PlusJakartaSans-SemiBold', bold: 'PlusJakartaSans-Bold' },
};

const SHADOW_RN = {
  none:   null,
  subtle: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 3,  elevation: 2 },
  medium: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.10, shadowRadius: 6,  elevation: 4 },
  strong: { shadowColor: '#000', shadowOffset: { width: 0, height: 10 },shadowOpacity: 0.18, shadowRadius: 25, elevation: 8 },
};

// ─── Tokens ──────────────────────────────────────────────────

function genTokens(prefs) {
  const { colors, borders: { radius }, spacing: { unit } } = prefs;
  const fonts = FONT_NATIVE_NAMES[prefs.typography.fontFamily] ?? FONT_NATIVE_NAMES['Inter'];

  return `// Auto-generated by quickly-react Design System Studio
// Edit this file to customise your design tokens.

export const COLOR = {
  PRIMARY:       '${colors.primary}',
  PRIMARY_LIGHT: '${colors.primaryLight}',
  PRIMARY_DARK:  '${colors.primaryDark}',
  BG_ACCENT:     '${colors.bgAccent}',

  NEUTRAL_50:  '${colors.neutral50}',
  NEUTRAL_100: '${colors.neutral100}',
  NEUTRAL_200: '${colors.neutral200}',
  NEUTRAL_300: '${colors.neutral300}',
  NEUTRAL_400: '${colors.neutral400}',
  NEUTRAL_500: '${colors.neutral500}',
  NEUTRAL_600: '${colors.neutral600}',
  NEUTRAL_700: '${colors.neutral700}',
  NEUTRAL_800: '${colors.neutral800}',
  NEUTRAL_900: '${colors.neutral900}',

  SUCCESS: '${colors.success}',
  WARNING: '${colors.warning}',
  ERROR:   '${colors.error}',
  INFO:    '${colors.info}',

  BG_PRIMARY:   '${colors.bgPrimary}',
  BG_SECONDARY: '${colors.bgSecondary}',
  BG_TERTIARY:  '${colors.bgTertiary}',
  BORDER:       '${colors.border}',

  TEXT_PRIMARY:   '${colors.textPrimary}',
  TEXT_SECONDARY: '${colors.textSecondary}',
  TEXT_TERTIARY:  '${colors.textTertiary}',
  TEXT_INVERSE:   '${colors.textInverse}',

  WHITE: '#FFFFFF',
  BLACK: '#000000',
} as const;

export const FONT_FAMILY = {
  regular:  '${fonts.regular}',
  medium:   '${fonts.medium}',
  semiBold: '${fonts.semiBold}',
  bold:     '${fonts.bold}',
} as const;

export const RADIUS = {
  none: 0,
  sm:   ${Math.round(radius * 0.5)},
  md:   ${radius},
  lg:   ${Math.round(radius * 1.5)},
  xl:   ${radius * 2},
  full: 9999,
} as const;

export const UNIT = ${unit}; // Base spacing unit in px. m1=1×UNIT, m2=2×UNIT, etc.
`;
}

// ─── textProps ───────────────────────────────────────────────

function genTextProps(prefs) {
  const { colors } = prefs;

  return `// Auto-generated by quickly-react Design System Studio
import { Platform } from 'react-native';
import { IStyleProps, TCommonPropStyle } from 'quickly-react';
import { TextProps } from 'react-native';
import { COLOR, FONT_FAMILY } from './tokens';

type TPropParam = { propName: string; obj: any; isDefault?: boolean };

const FONT_WEB = "'${prefs.typography.fontFamily}', sans-serif";

export const textProps: Array<TPropParam> = [
  // ── Weight variants ───────────────────────────────────────
  {
    propName: 'regular',
    obj: { style: { fontWeight: '400', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.regular } },
    isDefault: true,
  },
  {
    propName: 'medium',
    obj: { style: { fontWeight: '500', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.medium } },
  },
  {
    propName: 'semiBold',
    obj: { style: { fontWeight: '600', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.semiBold } },
  },
  {
    propName: 'bold',
    obj: { style: { fontWeight: '700', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.bold } },
  },

  // ── Heading scale ─────────────────────────────────────────
  { propName: 'h1', obj: { style: { fontSize: 48, lineHeight: 58, fontWeight: '700', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.bold } } },
  { propName: 'h2', obj: { style: { fontSize: 36, lineHeight: 44, fontWeight: '700', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.bold } } },
  { propName: 'h3', obj: { style: { fontSize: 24, lineHeight: 30, fontWeight: '600', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.semiBold } } },
  { propName: 'h4', obj: { style: { fontSize: 20, lineHeight: 26, fontWeight: '600', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.semiBold } } },
  { propName: 'h5', obj: { style: { fontSize: 17, lineHeight: 22, fontWeight: '600', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.semiBold } } },
  { propName: 'h6', obj: { style: { fontSize: 15, lineHeight: 20, fontWeight: '600', fontFamily: Platform.OS === 'web' ? FONT_WEB : FONT_FAMILY.semiBold } } },

  // ── Body scale ────────────────────────────────────────────
  { propName: 'bodyLg',  obj: { style: { fontSize: 17, lineHeight: 26 } } },
  { propName: 'body',    obj: { style: { fontSize: 15, lineHeight: 22 } }, isDefault: true },
  { propName: 'bodySm',  obj: { style: { fontSize: 13, lineHeight: 20 } } },
  { propName: 'caption', obj: { style: { fontSize: 11, lineHeight: 16 } } },

  // ── Alignment ─────────────────────────────────────────────
  { propName: 'center', obj: { style: { textAlign: 'center' } } },
  { propName: 'right',  obj: { style: { textAlign: 'right'  } } },

  // ── Color variants ────────────────────────────────────────
  {
    propName: 'colorDefault',
    obj: { theme: { light: { color: COLOR.TEXT_PRIMARY }, dark: { color: COLOR.WHITE } } },
    isDefault: true,
  },
  {
    propName: 'colorMuted',
    obj: { theme: { light: { color: COLOR.TEXT_SECONDARY }, dark: { color: COLOR.NEUTRAL_400 } } },
  },
  { propName: 'colorPrimary',   obj: { style: { color: COLOR.PRIMARY } } },
  { propName: 'colorSuccess',   obj: { style: { color: COLOR.SUCCESS } } },
  { propName: 'colorError',     obj: { style: { color: COLOR.ERROR   } } },
  { propName: 'colorWarning',   obj: { style: { color: COLOR.WARNING } } },
  { propName: 'colorWhite',     obj: { style: { color: COLOR.WHITE   } } },
  { propName: 'colorInverse',   obj: { style: { color: COLOR.TEXT_INVERSE } } },
];

export interface ITextProps extends TextProps, IStyleProps, TCommonPropStyle {
  // Weight
  regular?: boolean;
  medium?: boolean;
  semiBold?: boolean;
  bold?: boolean;
  // Scale
  h1?: boolean; h2?: boolean; h3?: boolean; h4?: boolean; h5?: boolean; h6?: boolean;
  bodyLg?: boolean; body?: boolean; bodySm?: boolean; caption?: boolean;
  // Alignment
  center?: boolean; right?: boolean;
  // Color
  colorDefault?: boolean; colorMuted?: boolean; colorPrimary?: boolean;
  colorSuccess?: boolean; colorError?: boolean; colorWarning?: boolean;
  colorWhite?: boolean; colorInverse?: boolean;
}
`;
}

// ─── viewProps ───────────────────────────────────────────────

function genViewProps(prefs) {
  const { colors, borders: { radius }, shadows: { style: shadowStyle } } = prefs;
  const shadow = SHADOW_RN[shadowStyle];
  const shadowCode = shadow
    ? `{ shadowColor: '${shadow.shadowColor}', shadowOffset: { width: ${shadow.shadowOffset.width}, height: ${shadow.shadowOffset.height} }, shadowOpacity: ${shadow.shadowOpacity}, shadowRadius: ${shadow.shadowRadius}, elevation: ${shadow.elevation} }`
    : '{}';

  return `// Auto-generated by quickly-react Design System Studio
import { IStyleProps, TCommonPropStyle } from 'quickly-react';
import { ViewProps } from 'react-native';
import { COLOR, RADIUS } from './tokens';

type TPropParam = { propName: string; obj: any; isDefault?: boolean };

export const viewProps: Array<TPropParam> = [
  // ── Theme-aware backgrounds ───────────────────────────────
  {
    propName: 'bgSurface',
    obj: { theme: { light: { backgroundColor: COLOR.BG_PRIMARY   }, dark: { backgroundColor: '#1A1A1A' } } },
    isDefault: true,
  },
  {
    propName: 'bgSurface2',
    obj: { theme: { light: { backgroundColor: COLOR.BG_SECONDARY }, dark: { backgroundColor: '#242424' } } },
  },
  {
    propName: 'bgSurface3',
    obj: { theme: { light: { backgroundColor: COLOR.BG_TERTIARY  }, dark: { backgroundColor: '#2E2E2E' } } },
  },

  // ── Brand backgrounds ─────────────────────────────────────
  { propName: 'bgPrimary',      obj: { style: { backgroundColor: COLOR.PRIMARY      } } },
  { propName: 'bgPrimaryLight', obj: { style: { backgroundColor: COLOR.PRIMARY_LIGHT } } },
  { propName: 'bgAccent',       obj: { style: { backgroundColor: COLOR.BG_ACCENT    } } },

  // ── Semantic backgrounds ──────────────────────────────────
  { propName: 'bgSuccess', obj: { style: { backgroundColor: 'rgba(16,185,129,0.12)'  } } },
  { propName: 'bgError',   obj: { style: { backgroundColor: 'rgba(239,68,68,0.12)'   } } },
  { propName: 'bgWarning', obj: { style: { backgroundColor: 'rgba(245,158,11,0.12)'  } } },
  { propName: 'bgInfo',    obj: { style: { backgroundColor: 'rgba(59,130,246,0.12)'  } } },

  // ── Border radius ─────────────────────────────────────────
  { propName: 'roundNone', obj: { style: { borderRadius: RADIUS.none } } },
  { propName: 'roundSm',   obj: { style: { borderRadius: RADIUS.sm   } } },
  { propName: 'roundMd',   obj: { style: { borderRadius: RADIUS.md   } } },
  { propName: 'roundLg',   obj: { style: { borderRadius: RADIUS.lg   } } },
  { propName: 'roundXl',   obj: { style: { borderRadius: RADIUS.xl   } } },
  { propName: 'roundFull', obj: { style: { borderRadius: RADIUS.full } } },

  // ── Borders ───────────────────────────────────────────────
  { propName: 'bordered',       obj: { style: { borderWidth: 1,   borderColor: COLOR.BORDER,   borderStyle: 'solid' } } },
  { propName: 'borderedPrimary',obj: { style: { borderWidth: 1.5, borderColor: COLOR.PRIMARY,  borderStyle: 'solid' } } },
  { propName: 'borderedError',  obj: { style: { borderWidth: 1.5, borderColor: COLOR.ERROR,    borderStyle: 'solid' } } },

  // ── Elevation / shadows ───────────────────────────────────
  { propName: 'elevated', obj: { style: ${shadowCode} } },
];

export interface IViewProps {
  bgSurface?: boolean; bgSurface2?: boolean; bgSurface3?: boolean;
  bgPrimary?: boolean; bgPrimaryLight?: boolean; bgAccent?: boolean;
  bgSuccess?: boolean; bgError?: boolean; bgWarning?: boolean; bgInfo?: boolean;
  roundNone?: boolean; roundSm?: boolean; roundMd?: boolean; roundLg?: boolean; roundXl?: boolean; roundFull?: boolean;
  bordered?: boolean; borderedPrimary?: boolean; borderedError?: boolean;
  elevated?: boolean;
}
`;
}

// ─── index.tsx ───────────────────────────────────────────────

function genIndex(prefs) {
  const { colors, spacing: { unit } } = prefs;

  return `// Auto-generated by quickly-react Design System Studio
import { createBase, IStyleProps, TCommonPropStyle } from 'quickly-react';
import * as RN from 'react-native';
import {
  ViewProps, TouchableOpacityProps, PressableProps, TextProps,
  ScrollViewProps,
} from 'react-native';
import { textProps, ITextProps } from './textProps';
import { viewProps, IViewProps } from './viewProps';
import { COLOR, UNIT } from './tokens';

export interface IColProps
  extends ViewProps, PressableProps, IStyleProps, TCommonPropStyle, IViewProps {
  style?: any;
  children?: any;
}
export interface IRowProps extends IColProps {}

const BaseDS = createBase<IColProps, IRowProps, ITextProps>({
  RN,
  addTextProps: textProps,
  addViewProps:  viewProps,
  commonStyles:  {},
  tokens: {
    borderColor:        COLOR.BORDER,
    textColorPrimary:   COLOR.TEXT_PRIMARY,
    textColorSecondary: COLOR.TEXT_SECONDARY,
    textColorTertiary:  COLOR.TEXT_TERTIARY,
    bgColorPrimary:     COLOR.BG_PRIMARY,
    bgColorSecondary:   COLOR.BG_SECONDARY,
    mainColor:          COLOR.PRIMARY,
    unit:               UNIT,
  },
});

export const Col      = BaseDS.Col;
export const Row      = BaseDS.Row;
export const Text     = BaseDS.Text;
export const Grid     = BaseDS.Grid;
export const RatioCol = BaseDS.RatioCol;

export * from './tokens';
export * from './textProps';
export * from './viewProps';
`;
}

// ─── Button.tsx ──────────────────────────────────────────────

function genButton(prefs) {
  const { borders: { radius }, spacing: { unit } } = prefs;

  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { TouchableOpacity, ActivityIndicator } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface IButtonProps {
  title: string;
  onPress?: () => void;
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  fullWidth?: boolean;
}

const VARIANT: Record<ButtonVariant, { container: any; textColor: string }> = {
  primary:     { container: { backgroundColor: COLOR.PRIMARY,      borderWidth: 0    }, textColor: COLOR.TEXT_INVERSE },
  secondary:   { container: { backgroundColor: COLOR.BG_ACCENT,    borderWidth: 1.5, borderColor: COLOR.PRIMARY }, textColor: COLOR.PRIMARY },
  ghost:       { container: { backgroundColor: 'transparent',       borderWidth: 1.5, borderColor: COLOR.BORDER  }, textColor: COLOR.TEXT_PRIMARY },
  destructive: { container: { backgroundColor: COLOR.ERROR,         borderWidth: 0    }, textColor: COLOR.WHITE },
};

const SIZE: Record<ButtonSize, { ph: number; pv: number; fs: number }> = {
  sm: { ph: UNIT * 2,   pv: UNIT * 0.875, fs: 13 },
  md: { ph: UNIT * 2.5, pv: UNIT * 1.25,  fs: 14 },
  lg: { ph: UNIT * 3.5, pv: UNIT * 1.625, fs: 16 },
};

export const Button = ({
  title,
  onPress,
  variant = 'primary',
  size = 'md',
  disabled = false,
  loading = false,
  leftIcon,
  rightIcon,
  fullWidth = false,
}: IButtonProps) => {
  const v = VARIANT[variant];
  const s = SIZE[size];

  return (
    <TouchableOpacity
      onPress={disabled || loading ? undefined : onPress}
      activeOpacity={0.75}
      style={fullWidth ? { alignSelf: 'stretch' } : undefined}
    >
      <Row
        middle
        style={[
          v.container,
          {
            paddingHorizontal: s.ph,
            paddingVertical:   s.pv,
            borderRadius:      RADIUS.md,
            justifyContent:    'center',
            alignSelf:         fullWidth ? 'stretch' : 'flex-start',
            opacity:           disabled ? 0.5 : 1,
          },
        ]}
      >
        {loading ? (
          <ActivityIndicator
            size="small"
            color={variant === 'primary' || variant === 'destructive' ? COLOR.WHITE : COLOR.PRIMARY}
          />
        ) : (
          <>
            {leftIcon  && <Col style={{ marginRight: UNIT * 0.75 }}>{leftIcon}</Col>}
            <Text semiBold style={{ fontSize: s.fs, color: v.textColor }}>
              {title}
            </Text>
            {rightIcon && <Col style={{ marginLeft:  UNIT * 0.75 }}>{rightIcon}</Col>}
          </>
        )}
      </Row>
    </TouchableOpacity>
  );
};
`;
}

// ─── Input.tsx ───────────────────────────────────────────────

function genInput(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { TextInput, TextInputProps } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface IInputProps extends Omit<TextInputProps, 'style'> {
  label?: string;
  hint?: string;
  error?: string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  containerStyle?: any;
}

export const Input = ({
  label,
  hint,
  error,
  leftIcon,
  rightIcon,
  containerStyle,
  onFocus,
  onBlur,
  ...props
}: IInputProps) => {
  const [focused, setFocused] = useState(false);
  const hasError = !!error;

  const borderColor = hasError ? COLOR.ERROR
    : focused ? COLOR.PRIMARY
    : COLOR.BORDER;

  const ringColor = hasError ? 'rgba(239,68,68,0.12)'
    : focused ? COLOR.BG_ACCENT
    : 'transparent';

  return (
    <Col style={containerStyle}>
      {label && (
        <Text bodySm semiBold colorMuted style={{ marginBottom: UNIT * 0.75 }}>
          {label}
        </Text>
      )}
      <Row
        middle
        style={{
          borderWidth:   1.5,
          borderColor,
          borderRadius:  RADIUS.md,
          backgroundColor: COLOR.BG_PRIMARY,
          paddingHorizontal: UNIT * 1.5,
          shadowColor:   borderColor,
          shadowOffset:  { width: 0, height: 0 },
          shadowOpacity: focused || hasError ? 1 : 0,
          shadowRadius:  3,
          elevation:     0,
        }}
      >
        {leftIcon && <Col style={{ marginRight: UNIT }}>{leftIcon}</Col>}
        <TextInput
          {...props}
          onFocus={(e) => { setFocused(true);  onFocus?.(e); }}
          onBlur={(e)  => { setFocused(false); onBlur?.(e);  }}
          placeholderTextColor={COLOR.TEXT_TERTIARY}
          style={{
            flex: 1,
            paddingVertical: UNIT * 1.25,
            fontSize: 14,
            color: COLOR.TEXT_PRIMARY,
          }}
        />
        {rightIcon && <Col style={{ marginLeft: UNIT }}>{rightIcon}</Col>}
      </Row>
      {(hint || error) && (
        <Text caption style={{ marginTop: UNIT * 0.75, color: hasError ? COLOR.ERROR : COLOR.TEXT_TERTIARY }}>
          {error ?? hint}
        </Text>
      )}
    </Col>
  );
};
`;
}

// ─── Card.tsx ────────────────────────────────────────────────

function genCard(prefs) {
  const { shadows: { style: shadowStyle } } = prefs;
  const shadow = SHADOW_RN[shadowStyle];
  const shadowCode = shadow
    ? `shadowColor: '${shadow.shadowColor}', shadowOffset: { width: ${shadow.shadowOffset.width}, height: ${shadow.shadowOffset.height} }, shadowOpacity: ${shadow.shadowOpacity}, shadowRadius: ${shadow.shadowRadius}, elevation: ${shadow.elevation}`
    : '';

  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface ICardProps {
  title?: string;
  subtitle?: string;
  badge?: React.ReactNode;
  footer?: React.ReactNode;
  children?: React.ReactNode;
  elevated?: boolean;
  style?: any;
}

export const Card = ({
  title,
  subtitle,
  badge,
  footer,
  children,
  elevated = false,
  style,
}: ICardProps) => (
  <Col
    style={[
      {
        backgroundColor: COLOR.BG_PRIMARY,
        borderRadius:    RADIUS.lg,
        borderWidth:     1,
        borderColor:     COLOR.BORDER,
        padding:         UNIT * 3,
        ${shadowCode ? shadowCode + ',' : ''}
      },
      elevated && {
        shadowOpacity: 0.18,
        shadowRadius:  25,
        elevation:     8,
        borderWidth:   0,
      },
      style,
    ]}
  >
    {(title || badge) && (
      <Row middle style={{ marginBottom: UNIT * 1.5, justifyContent: 'space-between' }}>
        <Col flex1>
          {title && <Text h5 colorDefault>{title}</Text>}
          {subtitle && <Text bodySm colorMuted style={{ marginTop: 4 }}>{subtitle}</Text>}
        </Col>
        {badge && <Col style={{ marginLeft: UNIT }}>{badge}</Col>}
      </Row>
    )}
    {children}
    {footer && (
      <Col style={{ marginTop: UNIT * 2, paddingTop: UNIT * 2, borderTopWidth: 1, borderTopColor: COLOR.BORDER }}>
        {footer}
      </Col>
    )}
  </Col>
);
`;
}

// ─── Badge.tsx ───────────────────────────────────────────────

function genBadge(prefs) {
  const { borders: { radius } } = prefs;
  const badgeRadius = radius === 0 ? 0 : 9999;

  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export type BadgeVariant = 'success' | 'error' | 'warning' | 'info' | 'neutral' | 'primary';
export type BadgeSize    = 'sm' | 'md';

const VARIANT_CONFIG: Record<BadgeVariant, { bg: string; color: string }> = {
  success: { bg: 'rgba(16,185,129,0.12)',  color: '#059669' },
  error:   { bg: 'rgba(239,68,68,0.12)',   color: '#DC2626' },
  warning: { bg: 'rgba(245,158,11,0.12)',  color: '#D97706' },
  info:    { bg: 'rgba(59,130,246,0.12)',  color: '#2563EB' },
  neutral: { bg: COLOR.NEUTRAL_100,         color: COLOR.NEUTRAL_600 },
  primary: { bg: COLOR.BG_ACCENT,           color: COLOR.PRIMARY_DARK },
};

export interface IBadgeProps {
  label: string;
  variant?: BadgeVariant;
  size?: BadgeSize;
  dot?: boolean;
}

export const Badge = ({ label, variant = 'neutral', size = 'md', dot = false }: IBadgeProps) => {
  const config = VARIANT_CONFIG[variant];
  const fontSize = size === 'sm' ? 10 : 12;
  const ph = size === 'sm' ? UNIT * 0.75 : UNIT;
  const pv = size === 'sm' ? UNIT * 0.375 : UNIT * 0.5;

  return (
    <Row
      middle
      style={{
        paddingHorizontal: ph,
        paddingVertical:   pv,
        backgroundColor:   config.bg,
        borderRadius:      ${badgeRadius},
        alignSelf:         'flex-start',
      }}
    >
      {dot && (
        <Row style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: config.color, marginRight: 5 }} />
      )}
      <Text semiBold style={{ fontSize, color: config.color, lineHeight: fontSize * 1.3 }}>
        {label}
      </Text>
    </Row>
  );
};
`;
}

// ─── Dropdown.tsx (fixed: inner panel absorbs taps) ──────────

function genDropdown(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { Modal, TouchableOpacity, FlatList } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface IDropdownOption { label: string; value: string; }

export interface IDropdownProps {
  options: IDropdownOption[];
  value?: string;
  placeholder?: string;
  label?: string;
  error?: string;
  onChange?: (option: IDropdownOption) => void;
}

export const Dropdown = ({ options, value, placeholder = 'Select\u2026', label, error, onChange }: IDropdownProps) => {
  const [open, setOpen] = useState(false);
  const selected = options.find(o => o.value === value);

  return (
    <Col>
      {label && <Text bodySm semiBold colorMuted style={{ marginBottom: UNIT * 0.75 }}>{label}</Text>}
      <TouchableOpacity onPress={() => setOpen(true)} activeOpacity={0.8}>
        <Row middle style={{ borderWidth: 1.5, borderColor: error ? COLOR.ERROR : open ? COLOR.PRIMARY : COLOR.BORDER, borderRadius: RADIUS.md, backgroundColor: COLOR.BG_PRIMARY, paddingHorizontal: UNIT * 1.5, paddingVertical: UNIT * 1.25, justifyContent: 'space-between' }}>
          <Text body style={{ flex: 1, color: selected ? COLOR.TEXT_PRIMARY : COLOR.TEXT_TERTIARY }}>
            {selected ? selected.label : placeholder}
          </Text>
          <Text body colorMuted style={{ marginLeft: UNIT * 0.5 }}>\u25be</Text>
        </Row>
      </TouchableOpacity>
      {error && <Text caption style={{ marginTop: UNIT * 0.75, color: COLOR.ERROR }}>{error}</Text>}

      <Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}>
        {/* Outer layer closes on backdrop tap */}
        <TouchableOpacity style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' }} activeOpacity={1} onPress={() => setOpen(false)}>
          {/* Inner panel absorbs taps so they don't reach the backdrop */}
          <TouchableOpacity activeOpacity={1} onPress={() => {}}>
            <Col style={{ margin: UNIT * 2, marginBottom: UNIT * 3, backgroundColor: COLOR.BG_PRIMARY, borderRadius: RADIUS.lg, overflow: 'hidden', maxHeight: 320 }}>
              <Row style={{ padding: UNIT * 2, borderBottomWidth: 1, borderBottomColor: COLOR.BORDER }}>
                <Text h6 colorDefault style={{ flex: 1 }}>{label ?? 'Select'}</Text>
                <TouchableOpacity onPress={() => setOpen(false)} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
                  <Text body colorMuted>\u2715</Text>
                </TouchableOpacity>
              </Row>
              <FlatList
                data={options}
                keyExtractor={item => item.value}
                renderItem={({ item }) => (
                  <TouchableOpacity onPress={() => { onChange?.(item); setOpen(false); }} activeOpacity={0.7}>
                    <Row middle style={{ paddingHorizontal: UNIT * 2, paddingVertical: UNIT * 1.5, borderBottomWidth: 1, borderBottomColor: COLOR.BORDER, backgroundColor: item.value === value ? COLOR.BG_ACCENT : 'transparent', justifyContent: 'space-between' }}>
                      <Text body style={{ color: item.value === value ? COLOR.PRIMARY : COLOR.TEXT_PRIMARY, fontWeight: item.value === value ? '600' : '400' }}>
                        {item.label}
                      </Text>
                      {item.value === value && <Text body colorPrimary>\u2713</Text>}
                    </Row>
                  </TouchableOpacity>
                )}
              />
            </Col>
          </TouchableOpacity>
        </TouchableOpacity>
      </Modal>
    </Col>
  );
};
`;
}

// ─── IconButton.tsx ───────────────────────────────────────────

function genIconButton(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { TouchableOpacity } from 'react-native';
import { Col } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type IconButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
export type IconButtonSize    = 'sm' | 'md' | 'lg';

export interface IIconButtonProps {
  icon: React.ReactNode;
  onPress?: () => void;
  variant?: IconButtonVariant;
  size?: IconButtonSize;
  disabled?: boolean;
  rounded?: boolean;
  accessibilityLabel?: string;
}

const VARIANT_STYLES: Record<IconButtonVariant, any> = {
  primary:     { backgroundColor: COLOR.PRIMARY,   borderWidth: 0 },
  secondary:   { backgroundColor: COLOR.BG_ACCENT, borderWidth: 1.5, borderColor: COLOR.PRIMARY },
  ghost:       { backgroundColor: 'transparent',    borderWidth: 1.5, borderColor: COLOR.BORDER },
  destructive: { backgroundColor: COLOR.ERROR,      borderWidth: 0 },
};

const SIZE_MAP: Record<IconButtonSize, number> = { sm: 32, md: 40, lg: 48 };

export const IconButton = ({
  icon, onPress, variant = 'ghost', size = 'md', disabled = false, rounded = false, accessibilityLabel,
}: IIconButtonProps) => {
  const dim = SIZE_MAP[size];
  return (
    <TouchableOpacity onPress={disabled ? undefined : onPress} activeOpacity={0.75} accessibilityLabel={accessibilityLabel} accessibilityRole="button">
      <Col style={[VARIANT_STYLES[variant], { width: dim, height: dim, borderRadius: rounded ? dim / 2 : RADIUS.md, alignItems: 'center', justifyContent: 'center', opacity: disabled ? 0.5 : 1 }]}>
        {icon}
      </Col>
    </TouchableOpacity>
  );
};
`;
}

// ─── Textarea.tsx ─────────────────────────────────────────────

function genTextarea(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { TextInput, TextInputProps } from 'react-native';
import { Col, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface ITextareaProps extends Omit<TextInputProps, 'multiline' | 'style'> {
  label?: string;
  hint?: string;
  error?: string;
  rows?: number;
  containerStyle?: any;
}

export const Textarea = ({ label, hint, error, rows = 4, containerStyle, onFocus, onBlur, ...props }: ITextareaProps) => {
  const [focused, setFocused] = useState(false);
  const hasError = !!error;
  return (
    <Col style={containerStyle}>
      {label && <Text bodySm semiBold colorMuted style={{ marginBottom: UNIT * 0.75 }}>{label}</Text>}
      <TextInput
        {...props}
        multiline
        numberOfLines={rows}
        textAlignVertical="top"
        onFocus={e => { setFocused(true); onFocus?.(e); }}
        onBlur={e  => { setFocused(false); onBlur?.(e); }}
        placeholderTextColor={COLOR.TEXT_TERTIARY}
        style={{
          borderWidth: 1.5,
          borderColor: hasError ? COLOR.ERROR : focused ? COLOR.PRIMARY : COLOR.BORDER,
          borderRadius: RADIUS.md,
          backgroundColor: COLOR.BG_PRIMARY,
          paddingHorizontal: UNIT * 1.5,
          paddingVertical:   UNIT * 1.25,
          fontSize: 14,
          color: COLOR.TEXT_PRIMARY,
          minHeight: rows * 24,
          shadowColor:   hasError ? COLOR.ERROR : COLOR.PRIMARY,
          shadowOffset:  { width: 0, height: 0 },
          shadowOpacity: focused || hasError ? 0.2 : 0,
          shadowRadius:  4,
          elevation:     0,
        }}
      />
      {(hint || error) && (
        <Text caption style={{ marginTop: UNIT * 0.75, color: hasError ? COLOR.ERROR : COLOR.TEXT_TERTIARY }}>
          {error ?? hint}
        </Text>
      )}
    </Col>
  );
};
`;
}

// ─── Checkbox.tsx ─────────────────────────────────────────────

function genCheckbox(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useEffect, useRef } from 'react';
import { TouchableOpacity, Animated } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface ICheckboxProps {
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  hint?: string;
  error?: string;
  disabled?: boolean;
  indeterminate?: boolean;
}

export const Checkbox = ({ checked = false, onChange, label, hint, error, disabled = false, indeterminate = false }: ICheckboxProps) => {
  const scale = useRef(new Animated.Value(checked || indeterminate ? 1 : 0)).current;

  useEffect(() => {
    Animated.spring(scale, {
      toValue: checked || indeterminate ? 1 : 0,
      useNativeDriver: true,
      tension: 300,
      friction: 20,
    }).start();
  }, [checked, indeterminate]);

  const active = checked || indeterminate;

  return (
    <TouchableOpacity onPress={() => !disabled && onChange?.(!checked)} activeOpacity={0.7} accessibilityRole="checkbox">
      <Row middle style={{ gap: UNIT * 1.25, opacity: disabled ? 0.5 : 1 }}>
        <Col style={{ width: 20, height: 20, borderRadius: RADIUS.sm, borderWidth: 2, borderColor: active ? COLOR.PRIMARY : error ? COLOR.ERROR : COLOR.NEUTRAL_300, backgroundColor: active ? COLOR.PRIMARY : 'transparent', alignItems: 'center', justifyContent: 'center' }}>
          <Animated.Text style={{ color: COLOR.WHITE, fontSize: indeterminate ? 14 : 11, fontWeight: '800', lineHeight: 14, transform: [{ scale }] }}>
            {indeterminate ? '\u2212' : '\u2713'}
          </Animated.Text>
        </Col>
        {label && (
          <Col flex1>
            <Text body style={{ color: error ? COLOR.ERROR : COLOR.TEXT_PRIMARY }}>{label}</Text>
            {hint && <Text caption colorMuted style={{ marginTop: 2 }}>{hint}</Text>}
          </Col>
        )}
      </Row>
      {error && !label && <Text caption style={{ marginTop: UNIT * 0.5, color: COLOR.ERROR }}>{error}</Text>}
    </TouchableOpacity>
  );
};
`;
}

// ─── Radio.tsx ────────────────────────────────────────────────

function genRadio(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { TouchableOpacity } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export interface IRadioOption { label: string; value: string; hint?: string; }

export interface IRadioGroupProps {
  options: IRadioOption[];
  value?: string;
  onChange?: (value: string) => void;
  label?: string;
  error?: string;
  disabled?: boolean;
  direction?: 'vertical' | 'horizontal';
}

export const RadioGroup = ({ options, value, onChange, label, error, disabled = false, direction = 'vertical' }: IRadioGroupProps) => (
  <Col>
    {label && <Text bodySm semiBold colorMuted style={{ marginBottom: UNIT }}>{label}</Text>}
    <Col style={direction === 'horizontal' ? { flexDirection: 'row', flexWrap: 'wrap', gap: UNIT * 2 } : { gap: UNIT * 1.25 }}>
      {options.map(option => {
        const active = option.value === value;
        return (
          <TouchableOpacity key={option.value} onPress={() => !disabled && onChange?.(option.value)} activeOpacity={0.7} accessibilityRole="radio">
            <Row middle style={{ gap: UNIT * 1.25, opacity: disabled ? 0.5 : 1 }}>
              <Col style={{ width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: active ? COLOR.PRIMARY : error ? COLOR.ERROR : COLOR.NEUTRAL_300, alignItems: 'center', justifyContent: 'center' }}>
                {active && <Col style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: COLOR.PRIMARY }} />}
              </Col>
              <Col>
                <Text body style={{ color: COLOR.TEXT_PRIMARY }}>{option.label}</Text>
                {option.hint && <Text caption colorMuted style={{ marginTop: 2 }}>{option.hint}</Text>}
              </Col>
            </Row>
          </TouchableOpacity>
        );
      })}
    </Col>
    {error && <Text caption style={{ marginTop: UNIT * 0.75, color: COLOR.ERROR }}>{error}</Text>}
  </Col>
);
`;
}

// ─── Switch.tsx ───────────────────────────────────────────────

function genSwitch(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useEffect, useRef } from 'react';
import { TouchableOpacity, Animated } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export interface ISwitchProps {
  value?: boolean;
  onChange?: (v: boolean) => void;
  label?: string;
  hint?: string;
  disabled?: boolean;
  size?: 'sm' | 'md';
}

export const Switch = ({ value = false, onChange, label, hint, disabled = false, size = 'md' }: ISwitchProps) => {
  const trackW   = size === 'sm' ? 36 : 44;
  const trackH   = size === 'sm' ? 20 : 24;
  const thumbSz  = size === 'sm' ? 16 : 20;
  const travel   = trackW - thumbSz - 4;

  const tx    = useRef(new Animated.Value(value ? travel : 0)).current;
  const color = useRef(new Animated.Value(value ? 1 : 0)).current;

  useEffect(() => {
    Animated.parallel([
      Animated.spring(tx,    { toValue: value ? travel : 0, useNativeDriver: true,  tension: 300, friction: 20 }),
      Animated.timing(color, { toValue: value ? 1 : 0,       useNativeDriver: false, duration: 150 }),
    ]).start();
  }, [value]);

  const trackBg = color.interpolate({ inputRange: [0, 1], outputRange: [COLOR.NEUTRAL_200, COLOR.PRIMARY] });

  return (
    <TouchableOpacity onPress={() => !disabled && onChange?.(!value)} activeOpacity={0.8} accessibilityRole="switch">
      <Row middle style={{ gap: UNIT * 1.25, opacity: disabled ? 0.5 : 1 }}>
        <Animated.View style={{ width: trackW, height: trackH, borderRadius: trackH / 2, backgroundColor: trackBg, padding: 2, justifyContent: 'center' }}>
          <Animated.View style={{ width: thumbSz, height: thumbSz, borderRadius: thumbSz / 2, backgroundColor: COLOR.WHITE, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.15, shadowRadius: 2, elevation: 2, transform: [{ translateX: tx }] }} />
        </Animated.View>
        {(label || hint) && (
          <Col>
            {label && <Text body style={{ color: COLOR.TEXT_PRIMARY }}>{label}</Text>}
            {hint  && <Text caption colorMuted style={{ marginTop: 2 }}>{hint}</Text>}
          </Col>
        )}
      </Row>
    </TouchableOpacity>
  );
};
`;
}

// ─── Label.tsx ────────────────────────────────────────────────

function genLabel() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export interface ILabelProps {
  children: React.ReactNode;
  required?: boolean;
  optional?: boolean;
  style?: any;
}

export const Label = ({ children, required, optional, style }: ILabelProps) => (
  <Row middle style={[{ gap: UNIT * 0.5 }, style]}>
    <Text bodySm semiBold colorDefault>{children}</Text>
    {required && <Text caption style={{ color: COLOR.ERROR }}>*</Text>}
    {optional && <Text caption colorMuted>(optional)</Text>}
  </Row>
);
`;
}

// ─── HelperText.tsx ───────────────────────────────────────────

function genHelperText() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export type HelperVariant = 'default' | 'error' | 'success' | 'warning';

export interface IHelperTextProps {
  children: React.ReactNode;
  variant?: HelperVariant;
  style?: any;
}

const COLOR_MAP: Record<HelperVariant, string> = {
  default: COLOR.TEXT_TERTIARY,
  error:   COLOR.ERROR,
  success: COLOR.SUCCESS,
  warning: COLOR.WARNING,
};

const ICON_MAP: Record<HelperVariant, string> = {
  default: '',
  error:   '\u26a0 ',
  success: '\u2713 ',
  warning: '\u0021 ',
};

export const HelperText = ({ children, variant = 'default', style }: IHelperTextProps) => (
  <Text caption style={[{ color: COLOR_MAP[variant], marginTop: UNIT * 0.75 }, style]}>
    {ICON_MAP[variant]}{children}
  </Text>
);
`;
}

// ─── FormField.tsx ────────────────────────────────────────────

function genFormField() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Col } from '../index';
import { Label } from './Label';
import { HelperText } from './HelperText';
import { UNIT } from '../tokens';

export interface IFormFieldProps {
  label?: string;
  required?: boolean;
  optional?: boolean;
  hint?: string;
  error?: string;
  children: React.ReactNode;
  style?: any;
}

export const FormField = ({ label, required, optional, hint, error, children, style }: IFormFieldProps) => (
  <Col style={[{ gap: UNIT * 0.75 }, style]}>
    {label && <Label required={required} optional={optional}>{label}</Label>}
    {children}
    {(error || hint) && <HelperText variant={error ? 'error' : 'default'}>{error ?? hint}</HelperText>}
  </Col>
);
`;
}

// ─── SearchBar.tsx ────────────────────────────────────────────

function genSearchBar(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { TextInput, TextInputProps, TouchableOpacity } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface ISearchBarProps extends Omit<TextInputProps, 'style'> {
  value?: string;
  onChangeText?: (text: string) => void;
  onClear?: () => void;
  containerStyle?: any;
}

export const SearchBar = ({ value = '', onChangeText, onClear, containerStyle, ...props }: ISearchBarProps) => {
  const [focused, setFocused] = useState(false);
  return (
    <Row middle style={[{ borderWidth: 1.5, borderColor: focused ? COLOR.PRIMARY : COLOR.BORDER, borderRadius: RADIUS.full, backgroundColor: COLOR.BG_SECONDARY, paddingHorizontal: UNIT * 1.5, paddingVertical: UNIT, gap: UNIT, shadowColor: COLOR.PRIMARY, shadowOffset: { width: 0, height: 0 }, shadowOpacity: focused ? 0.15 : 0, shadowRadius: 4, elevation: 0 }, containerStyle]}>
      <Text body style={{ color: COLOR.TEXT_TERTIARY, fontSize: 16 }}>\uD83D\uDD0D</Text>
      <TextInput
        {...props}
        value={value}
        onChangeText={onChangeText}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        placeholderTextColor={COLOR.TEXT_TERTIARY}
        returnKeyType="search"
        style={{ flex: 1, fontSize: 15, color: COLOR.TEXT_PRIMARY }}
      />
      {!!value && (
        <TouchableOpacity onPress={() => { onChangeText?.(''); onClear?.(); }} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Col style={{ width: 18, height: 18, borderRadius: 9, backgroundColor: COLOR.NEUTRAL_300, alignItems: 'center', justifyContent: 'center' }}>
            <Text style={{ color: COLOR.WHITE, fontSize: 10, fontWeight: '700' }}>\u2715</Text>
          </Col>
        </TouchableOpacity>
      )}
    </Row>
  );
};
`;
}

// ─── Toast.tsx ────────────────────────────────────────────────

function genToast(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Animated, TouchableOpacity } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

// ─── InfoBox — inline alert banner ───────────────────────────

export type AlertVariant = 'success' | 'warning' | 'error' | 'info';

export interface IInfoBoxProps {
  variant?: AlertVariant;
  title?: string;
  message: string;
  dismissible?: boolean;
  onDismiss?: () => void;
  action?: { label: string; onPress: () => void };
}

const ALERT: Record<AlertVariant, { bg: string; border: string; icon: string; text: string }> = {
  success: { bg: 'rgba(16,185,129,0.08)',  border: '#10B981', icon: '\u2713', text: '#059669' },
  warning: { bg: 'rgba(245,158,11,0.08)',  border: '#F59E0B', icon: '!',       text: '#D97706' },
  error:   { bg: 'rgba(239,68,68,0.08)',   border: '#EF4444', icon: '\u2715',  text: '#DC2626' },
  info:    { bg: 'rgba(59,130,246,0.08)',  border: '#3B82F6', icon: 'i',       text: '#2563EB' },
};

export const InfoBox = ({ variant = 'info', title, message, dismissible = false, onDismiss, action }: IInfoBoxProps) => {
  const c = ALERT[variant];
  return (
    <Row style={{ backgroundColor: c.bg, borderWidth: 1, borderColor: c.border + '40', borderLeftWidth: 3, borderLeftColor: c.border, borderRadius: RADIUS.md, padding: UNIT * 1.5, gap: UNIT * 1.25, alignItems: 'flex-start' }}>
      <Col style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: c.border, alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 }}>
        <Text style={{ color: COLOR.WHITE, fontSize: 11, fontWeight: '800', lineHeight: 14 }}>{c.icon}</Text>
      </Col>
      <Col flex1>
        {title && <Text body semiBold style={{ color: c.text, marginBottom: 2 }}>{title}</Text>}
        <Text body style={{ color: c.text, lineHeight: 22 }}>{message}</Text>
        {action && (
          <TouchableOpacity onPress={action.onPress} style={{ marginTop: UNIT }}>
            <Text bodySm semiBold style={{ color: c.border }}>{action.label} \u2192</Text>
          </TouchableOpacity>
        )}
      </Col>
      {dismissible && (
        <TouchableOpacity onPress={onDismiss} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Text body style={{ color: c.text, opacity: 0.6 }}>\u2715</Text>
        </TouchableOpacity>
      )}
    </Row>
  );
};

// ─── Toast system ─────────────────────────────────────────────

export interface IToast { id: string; variant: AlertVariant; message: string; title?: string; duration?: number; }

const ToastItem = ({ toast, onDismiss }: { toast: IToast; onDismiss: (id: string) => void }) => {
  const ty      = useRef(new Animated.Value(-60)).current;
  const opacity = useRef(new Animated.Value(0)).current;
  const c       = ALERT[toast.variant];

  const dismiss = useCallback(() => {
    Animated.parallel([
      Animated.timing(ty,      { toValue: -60, duration: 220, useNativeDriver: true }),
      Animated.timing(opacity, { toValue: 0,   duration: 220, useNativeDriver: true }),
    ]).start(() => onDismiss(toast.id));
  }, []);

  useEffect(() => {
    Animated.parallel([
      Animated.spring(ty,      { toValue: 0, useNativeDriver: true,  tension: 200, friction: 20 }),
      Animated.timing(opacity, { toValue: 1, useNativeDriver: true,  duration: 200 }),
    ]).start();
    const t = setTimeout(dismiss, toast.duration ?? 3500);
    return () => clearTimeout(t);
  }, []);

  return (
    <Animated.View style={{ transform: [{ translateY: ty }], opacity, marginBottom: UNIT }}>
      <Row style={{ backgroundColor: COLOR.BG_PRIMARY, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: c.border + '40', borderLeftWidth: 3, borderLeftColor: c.border, padding: UNIT * 1.5, gap: UNIT, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 8, elevation: 6 }}>
        <Col style={{ width: 18, height: 18, borderRadius: 9, backgroundColor: c.border, alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <Text style={{ color: COLOR.WHITE, fontSize: 10, fontWeight: '800' }}>{c.icon}</Text>
        </Col>
        <Col flex1>
          {toast.title && <Text bodySm semiBold style={{ color: c.text }}>{toast.title}</Text>}
          <Text bodySm style={{ color: COLOR.TEXT_PRIMARY }}>{toast.message}</Text>
        </Col>
        <TouchableOpacity onPress={dismiss} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Text body colorMuted>\u2715</Text>
        </TouchableOpacity>
      </Row>
    </Animated.View>
  );
};

export const ToastContainer = ({ toasts, onDismiss, position = 'top' }: { toasts: IToast[]; onDismiss: (id: string) => void; position?: 'top' | 'bottom' }) => (
  <Col style={{ position: 'absolute', left: UNIT * 2, right: UNIT * 2, ...(position === 'top' ? { top: UNIT * 6 } : { bottom: UNIT * 10 }), zIndex: 9999 }} pointerEvents="box-none">
    {toasts.map(t => <ToastItem key={t.id} toast={t} onDismiss={onDismiss} />)}
  </Col>
);

export const useToast = () => {
  const [toasts, setToasts] = useState<IToast[]>([]);
  const dismiss = useCallback((id: string) => setToasts(p => p.filter(t => t.id !== id)), []);
  const show = useCallback((variant: AlertVariant, message: string, opts?: { title?: string; duration?: number }) => {
    setToasts(p => [...p, { id: Math.random().toString(36).slice(2), variant, message, ...opts }]);
  }, []);
  return {
    toasts, dismiss,
    success: (msg: string, opts?: any) => show('success', msg, opts),
    warning: (msg: string, opts?: any) => show('warning', msg, opts),
    error:   (msg: string, opts?: any) => show('error',   msg, opts),
    info:    (msg: string, opts?: any) => show('info',    msg, opts),
  };
};
`;
}

// ─── Accordion.tsx ────────────────────────────────────────────

function genAccordion(prefs) {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { TouchableOpacity, Platform, UIManager, LayoutAnimation } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

if (Platform.OS === 'android' && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

export interface IAccordionItem { key: string; title: string; content: React.ReactNode; subtitle?: string; }

export interface IAccordionProps {
  items: IAccordionItem[];
  multiple?: boolean;
  defaultOpen?: string[];
}

export const Accordion = ({ items, multiple = false, defaultOpen = [] }: IAccordionProps) => {
  const [openKeys, setOpenKeys] = useState<string[]>(defaultOpen);

  const toggle = (key: string) => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setOpenKeys(prev =>
      multiple
        ? prev.includes(key) ? prev.filter(k => k !== key) : [...prev, key]
        : prev.includes(key) ? [] : [key]
    );
  };

  return (
    <Col style={{ borderWidth: 1, borderColor: COLOR.BORDER, borderRadius: RADIUS.lg, overflow: 'hidden' }}>
      {items.map((item, i) => {
        const isOpen = openKeys.includes(item.key);
        return (
          <Col key={item.key} style={i < items.length - 1 ? { borderBottomWidth: 1, borderBottomColor: COLOR.BORDER } : undefined}>
            <TouchableOpacity onPress={() => toggle(item.key)} activeOpacity={0.7}>
              <Row middle style={{ paddingHorizontal: UNIT * 2, paddingVertical: UNIT * 1.75, backgroundColor: isOpen ? COLOR.BG_SECONDARY : COLOR.BG_PRIMARY, justifyContent: 'space-between', gap: UNIT }}>
                <Col flex1>
                  <Text body semiBold colorDefault>{item.title}</Text>
                  {item.subtitle && <Text caption colorMuted style={{ marginTop: 2 }}>{item.subtitle}</Text>}
                </Col>
                <Text body colorMuted style={{ fontSize: 11, transform: [{ rotate: isOpen ? '180deg' : '0deg' }] }}>\u25bc</Text>
              </Row>
            </TouchableOpacity>
            {isOpen && (
              <Col style={{ paddingHorizontal: UNIT * 2, paddingVertical: UNIT * 2, backgroundColor: COLOR.BG_PRIMARY, borderTopWidth: 1, borderTopColor: COLOR.BORDER }}>
                {item.content}
              </Col>
            )}
          </Col>
        );
      })}
    </Col>
  );
};
`;
}

// ─── layouts/Dialog.tsx ───────────────────────────────────────

function genDialog() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Modal, KeyboardAvoidingView, Platform, TouchableOpacity, ScrollView } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type DialogSize = 'sm' | 'md' | 'lg' | 'full';

export interface IDialogProps {
  visible: boolean;
  onClose: () => void;
  title?: string;
  size?: DialogSize;
  children?: React.ReactNode;
  footer?: React.ReactNode;
  dismissible?: boolean;
}

const WIDTH: Record<DialogSize, any> = { sm: 340, md: 480, lg: 600, full: '95%' };

export const Dialog = ({ visible, onClose, title, size = 'md', children, footer, dismissible = true }: IDialogProps) => (
  <Modal visible={visible} transparent animationType="fade" statusBarTranslucent onRequestClose={dismissible ? onClose : undefined}>
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
      {/* Backdrop — closes dialog when tapped if dismissible */}
      <TouchableOpacity style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center', padding: UNIT * 2 }} activeOpacity={1} onPress={dismissible ? onClose : undefined}>
        {/* Panel — absorbs taps so they don't reach the backdrop */}
        <TouchableOpacity activeOpacity={1} onPress={() => {}} style={{ width: WIDTH[size], maxWidth: '100%' }}>
          <Col style={{ backgroundColor: COLOR.BG_PRIMARY, borderRadius: RADIUS.xl, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.25, shadowRadius: 40, elevation: 20 }}>
            {/* Header */}
            {title && (
              <Row middle style={{ paddingHorizontal: UNIT * 3, paddingVertical: UNIT * 2.5, borderBottomWidth: 1, borderBottomColor: COLOR.BORDER, justifyContent: 'space-between' }}>
                <Text h5 colorDefault style={{ flex: 1 }}>{title}</Text>
                <TouchableOpacity onPress={onClose} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
                  <Col style={{ width: 28, height: 28, borderRadius: 14, backgroundColor: COLOR.NEUTRAL_100, alignItems: 'center', justifyContent: 'center' }}>
                    <Text body colorMuted style={{ fontSize: 12 }}>\u2715</Text>
                  </Col>
                </TouchableOpacity>
              </Row>
            )}
            {/* Body */}
            <ScrollView><Col style={{ padding: UNIT * 3 }}>{children}</Col></ScrollView>
            {/* Footer */}
            {footer && (
              <Row middle style={{ paddingHorizontal: UNIT * 3, paddingVertical: UNIT * 2, borderTopWidth: 1, borderTopColor: COLOR.BORDER, justifyContent: 'flex-end', gap: UNIT }}>
                {footer}
              </Row>
            )}
          </Col>
        </TouchableOpacity>
      </TouchableOpacity>
    </KeyboardAvoidingView>
  </Modal>
);
`;
}

// ─── layouts/Tooltip.tsx ──────────────────────────────────────

function genTooltip() {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState, useRef } from 'react';
import { TouchableOpacity, Modal, View } from 'react-native';
import { Col, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type TooltipPosition = 'top' | 'bottom' | 'left' | 'right';

export interface ITooltipProps {
  content: string;
  position?: TooltipPosition;
  children: React.ReactNode;
  maxWidth?: number;
}

export const Tooltip = ({ content, position = 'top', children, maxWidth = 200 }: ITooltipProps) => {
  const [visible, setVisible] = useState(false);
  const [coords, setCoords] = useState({ x: 0, y: 0, w: 0, h: 0 });
  const ref = useRef<View>(null);

  const show = () => {
    ref.current?.measure((_fx, _fy, w, h, px, py) => {
      setCoords({ x: px, y: py, w, h });
      setVisible(true);
    });
  };

  const pos = (): any => {
    const g = 8;
    switch (position) {
      case 'top':    return { bottom: coords.y - g, left: coords.x + coords.w / 2 - maxWidth / 2 };
      case 'bottom': return { top: coords.y + coords.h + g, left: coords.x + coords.w / 2 - maxWidth / 2 };
      case 'left':   return { top: coords.y + coords.h / 2 - 14, right: coords.x - g };
      case 'right':  return { top: coords.y + coords.h / 2 - 14, left: coords.x + coords.w + g };
    }
  };

  return (
    <>
      <TouchableOpacity ref={ref as any} onPress={show} activeOpacity={0.8}>{children}</TouchableOpacity>
      <Modal visible={visible} transparent animationType="none" onRequestClose={() => setVisible(false)}>
        <TouchableOpacity style={{ flex: 1 }} activeOpacity={1} onPress={() => setVisible(false)}>
          <Col style={{ position: 'absolute', ...pos(), maxWidth, backgroundColor: COLOR.NEUTRAL_900, borderRadius: RADIUS.sm, paddingHorizontal: UNIT * 1.25, paddingVertical: UNIT * 0.75, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 10 }}>
            <Text caption style={{ color: COLOR.WHITE, lineHeight: 18 }}>{content}</Text>
          </Col>
        </TouchableOpacity>
      </Modal>
    </>
  );
};
`;
}

// ─── layouts/Popover.tsx ──────────────────────────────────────

function genPopover() {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState, useRef } from 'react';
import { TouchableOpacity, Modal, View } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type PopoverPosition = 'top' | 'bottom' | 'left' | 'right';

export interface IPopoverProps {
  trigger: React.ReactNode;
  content: React.ReactNode;
  title?: string;
  position?: PopoverPosition;
  width?: number;
}

export const Popover = ({ trigger, content, title, position = 'bottom', width = 260 }: IPopoverProps) => {
  const [visible, setVisible] = useState(false);
  const [coords, setCoords] = useState({ x: 0, y: 0, w: 0, h: 0 });
  const ref = useRef<View>(null);

  const show = () => {
    ref.current?.measure((_fx, _fy, w, h, px, py) => {
      setCoords({ x: px, y: py, w, h });
      setVisible(true);
    });
  };

  const pos = (): any => {
    const g = 8;
    switch (position) {
      case 'top':    return { bottom: coords.y - g,             left: coords.x };
      case 'bottom': return { top: coords.y + coords.h + g,     left: coords.x };
      case 'left':   return { top: coords.y,                    right: coords.x - g };
      case 'right':  return { top: coords.y,                    left: coords.x + coords.w + g };
    }
  };

  return (
    <>
      <TouchableOpacity ref={ref as any} onPress={show} activeOpacity={0.8}>{trigger}</TouchableOpacity>
      <Modal visible={visible} transparent animationType="fade" onRequestClose={() => setVisible(false)}>
        <TouchableOpacity style={{ flex: 1 }} activeOpacity={1} onPress={() => setVisible(false)}>
          {/* Panel absorbs taps */}
          <TouchableOpacity activeOpacity={1} onPress={() => {}} style={{ position: 'absolute', ...pos(), width }}>
            <Col style={{ backgroundColor: COLOR.BG_PRIMARY, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLOR.BORDER, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 12 }}>
              {title && (
                <Row middle style={{ paddingHorizontal: UNIT * 2, paddingVertical: UNIT * 1.5, borderBottomWidth: 1, borderBottomColor: COLOR.BORDER, justifyContent: 'space-between' }}>
                  <Text bodySm semiBold colorDefault>{title}</Text>
                  <TouchableOpacity onPress={() => setVisible(false)} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
                    <Text body colorMuted style={{ fontSize: 12 }}>\u2715</Text>
                  </TouchableOpacity>
                </Row>
              )}
              <Col style={{ padding: UNIT * 2 }}>{content}</Col>
            </Col>
          </TouchableOpacity>
        </TouchableOpacity>
      </Modal>
    </>
  );
};
`;}

// ─── README.md ───────────────────────────────────────────────

// ─── Section.tsx ─────────────────────────────────────────────

function genSection() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Col, Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export interface ISectionProps {
  title?: string;
  subtitle?: string;
  action?: React.ReactNode;
  children?: React.ReactNode;
  padded?: boolean;
  style?: any;
}

export const Section = ({
  title,
  subtitle,
  action,
  children,
  padded = true,
  style,
}: ISectionProps) => (
  <Col
    bgSurface2
    style={[padded && { paddingHorizontal: UNIT * 2, paddingVertical: UNIT * 3 }, style]}
  >
    {(title || action) && (
      <Row middle style={{ justifyContent: 'space-between', marginBottom: UNIT * 2.5 }}>
        <Col flex1>
          {title && <Text h5 colorDefault>{title}</Text>}
          {subtitle && <Text bodySm colorMuted style={{ marginTop: 4 }}>{subtitle}</Text>}
        </Col>
        {action && <Col style={{ marginLeft: UNIT }}>{action}</Col>}
      </Row>
    )}
    {children}
  </Col>
);
`;
}

// ─── layouts/LeftSidebar.tsx ──────────────────────────────────

function genLeftSidebar() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { ScrollView } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface ISidebarItem {
  key: string;
  label: string;
  icon?: React.ReactNode;
}

export interface ILeftSidebarProps {
  items: ISidebarItem[];
  activeKey?: string;
  onSelect?: (key: string) => void;
  logo?: React.ReactNode;
  footerSlot?: React.ReactNode;
  children?: React.ReactNode;
  sidebarWidth?: number;
}

export const LeftSidebar = ({
  items,
  activeKey,
  onSelect,
  logo,
  footerSlot,
  children,
  sidebarWidth = 220,
}: ILeftSidebarProps) => (
  <Row style={{ flex: 1 }}>
    {/* Sidebar */}
    <Col
      style={{
        width: sidebarWidth,
        backgroundColor: COLOR.NEUTRAL_900,
        paddingHorizontal: UNIT,
        paddingVertical: UNIT * 1.5,
      }}
    >
      {logo && (
        <Col style={{ paddingHorizontal: UNIT * 0.5, paddingVertical: UNIT, marginBottom: UNIT }}>
          {logo}
        </Col>
      )}
      <ScrollView showsVerticalScrollIndicator={false}>
        {items.map(item => {
          const active = item.key === activeKey;
          return (
            <Col
              key={item.key}
              onPress={() => onSelect?.(item.key)}
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                gap: UNIT,
                paddingHorizontal: UNIT * 1.5,
                paddingVertical: UNIT * 0.875,
                borderRadius: RADIUS.md,
                marginBottom: 2,
                backgroundColor: active ? COLOR.PRIMARY : 'transparent',
              }}
            >
              {item.icon && (
                <Col style={{ opacity: active ? 1 : 0.6 }}>{item.icon}</Col>
              )}
              <Text
                bodySm
                style={{
                  color: active ? COLOR.WHITE : 'rgba(255,255,255,0.55)',
                  fontWeight: active ? '600' : '400',
                }}
              >
                {item.label}
              </Text>
            </Col>
          );
        })}
      </ScrollView>
      {footerSlot && (
        <Col style={{ paddingHorizontal: UNIT * 0.5, paddingTop: UNIT }}>
          {footerSlot}
        </Col>
      )}
    </Col>
    {/* Main content */}
    <Col flex1 bgSurface2>
      {children}
    </Col>
  </Row>
);
`;
}

// ─── layouts/MasterDetail.tsx ─────────────────────────────────

function genMasterDetail() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { Col, Row } from '../index';
import { COLOR } from '../tokens';

export interface IMasterDetailProps {
  master: React.ReactNode;
  detail: React.ReactNode;
  detailWidth?: number;
  showDetail?: boolean;
}

export const MasterDetail = ({
  master,
  detail,
  detailWidth = 300,
  showDetail = true,
}: IMasterDetailProps) => (
  <Row style={{ flex: 1 }}>
    <Col
      flex1
      bgSurface
      style={showDetail ? { borderRightWidth: 1, borderRightColor: COLOR.BORDER } : undefined}
    >
      {master}
    </Col>
    {showDetail && (
      <Col style={{ width: detailWidth }} bgSurface2>
        {detail}
      </Col>
    )}
  </Row>
);
`;
}

// ─── layouts/Header.tsx ───────────────────────────────────────

function genHeader() {
  return `// Auto-generated by quickly-react Design System Studio
import React, { useState } from 'react';
import { Modal, TouchableOpacity, StatusBar } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export interface IHeaderProps {
  title?: string;
  logo?: React.ReactNode;
  rightSlot?: React.ReactNode;
  drawerContent?: React.ReactNode;
  onMenuPress?: () => void;
}

export const Header = ({
  title = 'App',
  logo,
  rightSlot,
  drawerContent,
  onMenuPress,
}: IHeaderProps) => {
  const [drawerOpen, setDrawerOpen] = useState(false);

  return (
    <>
      <Row
        middle
        bgSurface
        style={{
          height: 52,
          paddingHorizontal: UNIT * 2,
          borderBottomWidth: 1,
          borderBottomColor: COLOR.BORDER,
          justifyContent: 'space-between',
        }}
      >
        <TouchableOpacity
          onPress={drawerContent ? () => setDrawerOpen(true) : onMenuPress}
          activeOpacity={0.7}
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Col style={{ gap: 5, paddingVertical: 4 }}>
            {[0, 1, 2].map(i => (
              <Col key={i} style={{ width: 20, height: 2, backgroundColor: COLOR.TEXT_PRIMARY, borderRadius: 1 }} />
            ))}
          </Col>
        </TouchableOpacity>

        <Col style={{ position: 'absolute', left: 0, right: 0, alignItems: 'center', pointerEvents: 'none' }}>
          {logo ?? <Text h6 colorDefault>{title}</Text>}
        </Col>

        <Col style={{ marginLeft: 'auto' }}>{rightSlot}</Col>
      </Row>

      {drawerContent && (
        <Modal
          visible={drawerOpen}
          transparent
          animationType="slide"
          onRequestClose={() => setDrawerOpen(false)}
        >
          <Row style={{ flex: 1 }}>
            <Col
              style={{
                width: 280,
                backgroundColor: COLOR.NEUTRAL_900,
                paddingTop: StatusBar.currentHeight ?? 44,
              }}
            >
              {drawerContent}
            </Col>
            <TouchableOpacity
              style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' }}
              activeOpacity={1}
              onPress={() => setDrawerOpen(false)}
            />
          </Row>
        </Modal>
      )}
    </>
  );
};
`;
}

// ─── layouts/BottomNav.tsx ────────────────────────────────────

function genBottomNav() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { TouchableOpacity } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, UNIT } from '../tokens';

export interface IBottomNavTab {
  key: string;
  label: string;
  icon: React.ReactNode;
  badge?: number;
}

export interface IBottomNavProps {
  tabs: IBottomNavTab[];
  activeKey?: string;
  onSelect?: (key: string) => void;
}

export const BottomNav = ({ tabs, activeKey, onSelect }: IBottomNavProps) => (
  <Row
    middle
    bgSurface
    style={{
      height: 60,
      borderTopWidth: 1,
      borderTopColor: COLOR.BORDER,
      paddingBottom: UNIT,
    }}
  >
    {tabs.map(tab => {
      const active = tab.key === activeKey;
      return (
        <TouchableOpacity
          key={tab.key}
          style={{ flex: 1, alignItems: 'center', paddingTop: UNIT * 0.75 }}
          onPress={() => onSelect?.(tab.key)}
          activeOpacity={0.7}
        >
          <Col style={{ position: 'relative' }}>
            {tab.icon}
            {!!tab.badge && tab.badge > 0 && (
              <Col
                style={{
                  position: 'absolute',
                  top: -4,
                  right: -8,
                  minWidth: 16,
                  height: 16,
                  borderRadius: 8,
                  backgroundColor: COLOR.ERROR,
                  alignItems: 'center',
                  justifyContent: 'center',
                  paddingHorizontal: 3,
                }}
              >
                <Text style={{ fontSize: 9, fontWeight: '700', color: COLOR.WHITE }}>
                  {tab.badge > 99 ? '99+' : tab.badge}
                </Text>
              </Col>
            )}
          </Col>
          <Text
            style={{
              marginTop: 3,
              fontSize: 10,
              color: active ? COLOR.PRIMARY : COLOR.TEXT_TERTIARY,
              fontWeight: active ? '600' : '400',
            }}
          >
            {tab.label}
          </Text>
        </TouchableOpacity>
      );
    })}
  </Row>
);
`;
}

// ─── layouts/Tabs.tsx ────────────────────────────────────────

function genTabs() {
  return `// Auto-generated by quickly-react Design System Studio
import React from 'react';
import { ScrollView, TouchableOpacity } from 'react-native';
import { Col, Row, Text } from '../index';
import { COLOR, RADIUS, UNIT } from '../tokens';

export type TabsVariant = 'underline' | 'pill' | 'solid';

export interface ITab {
  key: string;
  label: string;
  content?: React.ReactNode;
}

export interface ITabsProps {
  tabs: ITab[];
  activeKey?: string;
  onSelect?: (key: string) => void;
  variant?: TabsVariant;
  scrollable?: boolean;
}

export const Tabs = ({
  tabs,
  activeKey,
  onSelect,
  variant = 'underline',
  scrollable = false,
}: ITabsProps) => {
  const TabBar = scrollable
    ? ({ children }: any) => (
        <ScrollView horizontal showsHorizontalScrollIndicator={false}>
          <Row>{children}</Row>
        </ScrollView>
      )
    : ({ children }: any) => <Row>{children}</Row>;

  return (
    <Col>
      {/* Tab bar */}
      <Col
        style={
          variant === 'pill'
            ? { flexDirection: 'row', padding: UNIT * 0.75, backgroundColor: COLOR.BG_TERTIARY, borderRadius: RADIUS.md + 4 }
            : variant === 'underline'
            ? { borderBottomWidth: 1.5, borderBottomColor: COLOR.BORDER }
            : undefined
        }
      >
        <TabBar>
          {tabs.map(tab => {
            const active = tab.key === activeKey;
            return (
              <TouchableOpacity
                key={tab.key}
                onPress={() => onSelect?.(tab.key)}
                activeOpacity={0.7}
                style={[
                  {
                    paddingVertical: variant === 'pill' ? UNIT * 0.625 : UNIT,
                    paddingHorizontal: variant === 'pill' ? UNIT * 1.5 : UNIT * 2,
                  },
                  variant === 'underline' && {
                    borderBottomWidth: 2,
                    borderBottomColor: active ? COLOR.PRIMARY : 'transparent',
                    marginBottom: -1.5,
                  },
                  variant === 'pill' && {
                    borderRadius: RADIUS.md,
                    backgroundColor: active ? COLOR.BG_PRIMARY : 'transparent',
                    shadowColor: '#000',
                    shadowOffset: { width: 0, height: 1 },
                    shadowOpacity: active ? 0.08 : 0,
                    shadowRadius: 3,
                    elevation: active ? 2 : 0,
                  },
                  variant === 'solid' && {
                    borderRadius: RADIUS.md,
                    borderWidth: 1,
                    borderColor: active ? COLOR.PRIMARY : COLOR.BORDER,
                    backgroundColor: active ? COLOR.PRIMARY : 'transparent',
                    marginRight: UNIT * 0.5,
                  },
                ]}
              >
                <Text
                  bodySm
                  style={{
                    fontWeight: active ? '600' : '400',
                    color:
                      variant === 'solid' && active
                        ? COLOR.WHITE
                        : active
                        ? COLOR.PRIMARY
                        : COLOR.TEXT_SECONDARY,
                  }}
                >
                  {tab.label}
                </Text>
              </TouchableOpacity>
            );
          })}
        </TabBar>
      </Col>

      {/* Active tab content */}
      {tabs.map(tab =>
        tab.key === activeKey && tab.content ? (
          <Col key={tab.key} style={{ marginTop: UNIT * 2 }}>
            {tab.content}
          </Col>
        ) : null
      )}
    </Col>
  );
};
`;
}

// ─── README.md ───────────────────────────────────────────────

function genReadme(prefs) {
  const { typography: { fontFamily }, borders: { radius }, spacing: { unit }, shadows: { style: shadowStyle }, colors } = prefs;

  return `# Design System

Auto-generated by [quickly-react Design System Studio](https://github.com/lequanghuylc/quickly-react).

## Settings used

| Token        | Value         |
|--------------|---------------|
| Brand color  | \`${colors.primary}\` |
| Font family  | ${fontFamily} |
| Border radius| ${radius}px   |
| Spacing unit | ${unit}px     |
| Shadow style | ${shadowStyle}|

## Setup

### 1. Install dependencies

\`\`\`bash
npm install quickly-react react-native
# or
yarn add quickly-react react-native
\`\`\`

### 2. Load fonts

In your Expo project, install and load the **${fontFamily}** font family.

\`\`\`bash
npx expo install @expo-google-fonts/${fontFamily.toLowerCase().replace(/ /g, '-')}
\`\`\`

Then in your \`App.tsx\`:
\`\`\`tsx
import { useFonts, ${fontFamily.replace(/ /g, '_')}_400Regular, ... } from '@expo-google-fonts/${fontFamily.toLowerCase().replace(/ /g, '-')}';

export default function App() {
  const [fontsLoaded] = useFonts({ '${fontFamily.replace(/ /g, '')}-Regular': ${fontFamily.replace(/ /g, '_')}_400Regular, ... });
  if (!fontsLoaded) return null;
  return <YourApp />;
}
\`\`\`

### 3. Use components

\`\`\`tsx
import { Col, Row, Text, Grid } from './design-system';
import { Button } from './design-system/components/Button';
import { Input  } from './design-system/components/Input';
import { Card   } from './design-system/components/Card';
import { Badge  } from './design-system/components/Badge';

export default function Example() {
  return (
    <Col flex1 bgSurface p4>
      <Text h3 colorDefault bold>Hello World</Text>
      <Text body colorMuted mt1>Built with quickly-react</Text>

      <Button title="Get Started" onPress={() => {}} />

      <Card title="My Card" subtitle="Subtitle here">
        <Text body colorDefault>Card content goes here.</Text>
      </Card>

      <Row mt2 style={{ gap: 8 }}>
        <Badge label="Active"  variant="success" dot />
        <Badge label="Draft"   variant="neutral" />
        <Badge label="Pending" variant="warning" dot />
      </Row>
    </Col>
  );
}
\`\`\`

## File structure

\`\`\`
design-system/
├── tokens.ts              ← All design tokens (colors, fonts, radii, spacing)
├── textProps.ts           ← Typography prop definitions
├── viewProps.ts           ← Layout & visual prop definitions
├── index.tsx              ← createBase() call — exports Col, Row, Text, Grid
├── components/
│   ├── Button.tsx         ← Button (primary, secondary, ghost, destructive, sizes)
│   ├── Input.tsx          ← Text input with label, error, icons
│   ├── Card.tsx           ← Card with title, badge, footer slots
│   ├── Badge.tsx          ← Status badge (success, error, warning, info…)
│   ├── Dropdown.tsx       ← Modal-based dropdown/select
│   └── Section.tsx        ← Page section container with title + action slot
└── layouts/
    ├── LeftSidebar.tsx    ← Dark sidebar + main content area
    ├── MasterDetail.tsx   ← List-detail split layout
    ├── Header.tsx         ← App header with hamburger + sliding drawer
    ├── BottomNav.tsx      ← Mobile bottom tab bar with badge support
    └── Tabs.tsx           ← Tabs (underline / pill / solid variants)
\`\`\`

Modify \`tokens.ts\` to adjust the design system, then re-run the Studio to regenerate components.
`;
}

// ─── Public API ──────────────────────────────────────────────

export function generateAllFiles(preferences) {
  return {
    // Core
    'tokens.ts':        genTokens(preferences),
    'textProps.ts':     genTextProps(preferences),
    'viewProps.ts':     genViewProps(preferences),
    'index.tsx':        genIndex(preferences),
    'README.md':        genReadme(preferences),
    // Components
    'Button.tsx':       genButton(preferences),
    'IconButton.tsx':   genIconButton(preferences),
    'Input.tsx':        genInput(preferences),
    'Textarea.tsx':     genTextarea(preferences),
    'Card.tsx':         genCard(preferences),
    'Badge.tsx':        genBadge(preferences),
    'Dropdown.tsx':     genDropdown(preferences),
    'Section.tsx':      genSection(),
    'Checkbox.tsx':     genCheckbox(preferences),
    'Radio.tsx':        genRadio(preferences),
    'Switch.tsx':       genSwitch(preferences),
    'Label.tsx':        genLabel(),
    'HelperText.tsx':   genHelperText(),
    'FormField.tsx':    genFormField(),
    'SearchBar.tsx':    genSearchBar(preferences),
    'Toast.tsx':        genToast(preferences),
    'Accordion.tsx':    genAccordion(preferences),
    // Layouts
    'LeftSidebar.tsx':  genLeftSidebar(),
    'MasterDetail.tsx': genMasterDetail(),
    'Header.tsx':       genHeader(),
    'BottomNav.tsx':    genBottomNav(),
    'Tabs.tsx':         genTabs(),
    'Dialog.tsx':       genDialog(),
    'Tooltip.tsx':      genTooltip(),
    'Popover.tsx':      genPopover(),
  };
}

export async function generateAndDownload(preferences) {
  const [{ default: JSZip }, { saveAs }] = await Promise.all([
    import('jszip'),
    import('file-saver'),
  ]);

  const files = generateAllFiles(preferences);
  const zip = new JSZip();
  const ds = zip.folder('design-system');
  const components = ds.folder('components');
  const layouts = ds.folder('layouts');

  ds.file('tokens.ts',    files['tokens.ts']);
  ds.file('textProps.ts', files['textProps.ts']);
  ds.file('viewProps.ts', files['viewProps.ts']);
  ds.file('index.tsx',    files['index.tsx']);
  ds.file('README.md',    files['README.md']);

  components.file('Button.tsx',     files['Button.tsx']);
  components.file('IconButton.tsx', files['IconButton.tsx']);
  components.file('Input.tsx',      files['Input.tsx']);
  components.file('Textarea.tsx',   files['Textarea.tsx']);
  components.file('Card.tsx',       files['Card.tsx']);
  components.file('Badge.tsx',      files['Badge.tsx']);
  components.file('Dropdown.tsx',   files['Dropdown.tsx']);
  components.file('Section.tsx',    files['Section.tsx']);
  components.file('Checkbox.tsx',   files['Checkbox.tsx']);
  components.file('Radio.tsx',      files['Radio.tsx']);
  components.file('Switch.tsx',     files['Switch.tsx']);
  components.file('Label.tsx',      files['Label.tsx']);
  components.file('HelperText.tsx', files['HelperText.tsx']);
  components.file('FormField.tsx',  files['FormField.tsx']);
  components.file('SearchBar.tsx',  files['SearchBar.tsx']);
  components.file('Toast.tsx',      files['Toast.tsx']);
  components.file('Accordion.tsx',  files['Accordion.tsx']);

  layouts.file('LeftSidebar.tsx',  files['LeftSidebar.tsx']);
  layouts.file('MasterDetail.tsx', files['MasterDetail.tsx']);
  layouts.file('Header.tsx',       files['Header.tsx']);
  layouts.file('BottomNav.tsx',    files['BottomNav.tsx']);
  layouts.file('Tabs.tsx',         files['Tabs.tsx']);
  layouts.file('Dialog.tsx',       files['Dialog.tsx']);
  layouts.file('Tooltip.tsx',      files['Tooltip.tsx']);
  layouts.file('Popover.tsx',      files['Popover.tsx']);

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, 'design-system.zip');
}
